# Generated by Django 4.2.3 on 2023-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_user_delete_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
