# Generated by Django 4.2.3 on 2023-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
