# Generated by Django 4.2.3 on 2023-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='helpful',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
