# Generated by Django 4.2.3 on 2023-08-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rating_helpful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='helpful',
        ),
    ]
