# Generated by Django 4.2.3 on 2023-11-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='rating',
        ),
    ]
